name: kototinder
description: >
  Кототиндер - тиндер котиков
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  connectivity_plus: ^2.3.0
  http: ^0.13.5
  cached_network_image: ^3.2.1
  flutter_card_swiper: ^7.0.2
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  mockito: ^5.4.2
  bloc_test: ^9.1.0
  build_runner: ^2.4.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/design/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.jpg"